<a href="https://colab.research.google.com/github/robertoricci/Analise-Financeira/blob/main/CVM_Os_Melhores_e_os_Piores_Fundos_de_Investimento_do_mes_Python_para_Investimentos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Baixar dados da CVM

*   Link para o vídeo: https://youtu.be/NHCUUZOvk7k
---
*   Base de Dados: http://dados.cvm.gov.br/

###Coletando os dados da CVM

In [1]:
import pandas as pd
pd.set_option("display.max_colwidth", 150)
import zipfile
import requests
from io import BytesIO
import os

#pd.options.display.float_format = '{:.2f}'.format

>Funções que buscam dados no site da CVM e retornam um DataFrame Pandas:

In [2]:
## funcção antiga quando era apenas csv
def busca_informes_cvm(ano, mes):
  url = 'http://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_{:02d}{:02d}.csv'.format(ano,mes)
  return pd.read_csv(url, sep=';')

In [55]:
def busca_informes_cvm_zip(ano, mes):
  url = 'http://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_{:02d}{:02d}.zip'.format(ano,mes)
  #buscar dados zipado
  filebytes = BytesIO(
      requests.get(url).content
  )
  path =  './fil_'+'{:02d}{:02d}'.format(ano,mes)
  os.makedirs(path, exist_ok=True)
  myzip = zipfile.ZipFile(filebytes)
  myzip.extractall(path )
  
  return pd.read_csv(path+'/inf_diario_fi_'+ '{:02d}{:02d}'.format(ano,mes)+'.csv', sep=';')

In [56]:
 #buscar dados do fundos no mesmo mes
 informes_diarios = busca_informes_cvm_zip(2022,5)

./fil_202205

,TP_FUNDO,CNPJ_FUNDO,DT_COMPTC,VL_TOTAL,VL_QUOTA,VL_PATRIM_LIQ,CAPTC_DIA,RESG_DIA,NR_COTST
0,FI,00.017.024/0001-53,2022-05-02,1045094.66,28.871262,1052342.82,0.0,0.0,1
1,FI,00.017.024/0001-53,2022-05-03,1045557.60,28.881645,1052721.26,0.0,0.0,1
2,FI,00.017.024/0001-53,2022-05-04,1046009.88,28.892292,1053109.34,0.0,0.0,1
3,FI,00.017.024/0001-53,2022-05-05,1046475.31,28.902647,1053486.76,0.0,0.0,1
4,FI,00.017.024/0001-53,2022-05-06,1046710.97,28.914378,1053914.37,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...
255530,FI,97.929.213/0001-34,2022-05-10,73933471.20,9.729054,73934205.65,0.0,0.0,2
255531,FI,97.929.213/0001-34,2022-05-11,73908795.33,9.725738,73909008.35,0.0,0.0,2
255532,FI,97.929.213/0001-34,2022-05-12,73980946.14,9.735164,73980637.45,0.0,0.0,2
255533,FI,97.929.213/0001-34,2022-05-13,74079254.40,9.748031,74078423.63,0.0,0.0,2
255534,FI,97.929.213/0001-34,2022-05-16,74153130.11,9.757684,74151776.94,0.0,0.0,2

In [62]:
#buscar cadastros dos fundos
def busca_cadastro_cvm():
  url = "http://dados.cvm.gov.br/dados/FI/CAD/DADOS/cad_fi.csv"
  return pd.read_csv(url, sep=';', encoding='ISO-8859-1')

In [63]:
cadastro_cvm = busca_cadastro_cvm()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DtypeWarning: Columns (14,17,18,20,22,24,27,37,38) have mixed types.Specify dtype option on import or set low_memory=False.
  """Entry point for launching an IPython kernel.

In [64]:
cadastro_cvm

,TP_FUNDO,CNPJ_FUNDO,DENOM_SOCIAL,DT_REG,DT_CONST,CD_CVM,DT_CANCEL,SIT,DT_INI_SIT,DT_INI_ATIV,...,ADMIN,PF_PJ_GESTOR,CPF_CNPJ_GESTOR,GESTOR,CNPJ_AUDITOR,AUDITOR,CNPJ_CUSTODIANTE,CUSTODIANTE,CNPJ_CONTROLADOR,CONTROLADOR
0,FACFIF,00.000.684/0001-21,DEUTSCHE BANK FDO APLIC QUOTAS FDO INV FINANCEIRO - MAX,2003-04-30,1994-12-20,19.0,2000-08-01,CANCELADA,2000-08-01,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FACFIF,00.000.731/0001-37,ITAMARITI CASH FUNDO APLICACAO QUOTAS FDOS INVESTIMENTO,2003-04-30,1994-05-18,40681.0,1996-01-26,CANCELADA,1996-01-26,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FACFIF,00.000.732/0001-81,FUNDO APLIC. QUOTAS DE F.I. SANTANDER CURTO PRAZO,2003-04-30,1994-05-24,27.0,1999-09-03,CANCELADA,1999-09-03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FACFIF,00.000.740/0001-28,FUNDO DE APLIC EM QUOTAS DE FUNDOS DE INV BMC 60 DIAS URV,2003-04-30,1994-05-23,40690.0,1996-06-10,CANCELADA,1996-06-10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FACFIF,00.000.749/0001-39,BALANCE FUNDO APLICACAO QUOTAS FUNDO INVESTIMENTO FINANCEIRO,2003-04-30,1994-05-12,35.0,2000-06-26,CANCELADA,2000-06-26,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67708,FUNCINE,28.849.405/0001-18,BTG PACTUAL INVESTIMAGE 1 - FUNDO DE FINANCIAMENTO DA INDUSTRIA CINEMATOGRAFICA NACIONAL - FUNCINE,2017-10-16,2017-10-09,417002.0,NaN,EM FUNCIONAMENTO NORMAL,2017-12-27,2017-12-27,...,BTG PACTUAL SERVIÇOS FINANCEIROS S/A DTVM,PJ,09.544.103/0001-97,INVESTIMAGE ADMINISTRADORA DE RECURSOS LTDA.,61.366.936/0001-25,ERNST & YOUNG AUDITORES INDEPENDENTES S/S,30.306.294/0001-45,BANCO BTG PACTUAL S/A,NaN,NaN
67709,FUNCINE,28.850.140/0001-78,FUNDO DE FINANCIAMENTO DA INDUSTRIA CINEMATOGRAFICA NACIONAL - FUNCINE - TIM,2017-10-16,2017-10-06,417001.0,NaN,EM FUNCIONAMENTO NORMAL,2017-12-26,2017-12-26,...,ID CORRETORA DE TITULOS E VALORES MOBILIARIOS S.A.,PJ,09.544.103/0001-97,INVESTIMAGE ADMINISTRADORA DE RECURSOS LTDA.,61.366.936/0001-25,ERNST & YOUNG AUDITORES INDEPENDENTES S/S,16.695.922/0001-09,ID CORRETORA DE TITULOS E VALORES MOBILIARIOS S.A.,NaN,NaN
67710,FUNCINE,28.912.043/0001-62,HAPVIDA - FUNDO DE FINANCIAMENTO DA INDUSTRIA CINEMATOGRAFICA NACIONAL - FUNCINE,2017-10-27,2017-10-19,417003.0,NaN,EM FUNCIONAMENTO NORMAL,2018-12-21,2018-12-21,...,ID CORRETORA DE TITULOS E VALORES MOBILIARIOS S.A.,PJ,09.544.103/0001-97,INVESTIMAGE ADMINISTRADORA DE RECURSOS LTDA.,19.280.834/0001-26,NEXT AUDITORES INDEPENDENTES S/S,16.695.922/0001-09,ID CORRETORA DE TITULOS E VALORES MOBILIARIOS S.A.,NaN,NaN
67711,FUNCINE,31.674.280/0001-47,BTG PACTUAL INVESTIMAGE III - FUNDO DE FINANCIAMENTO DA INDUSTRIA CINEMATOGRAFICA NACIONAL - FUNCINE,2018-10-26,2018-09-13,418001.0,NaN,FASE PRÉ-OPERACIONAL,2018-10-26,2018-10-26,...,BTG PACTUAL SERVIÇOS FINANCEIROS S/A DTVM,PJ,09.544.103/0001-97,INVESTIMAGE ADMINISTRADORA DE RECURSOS LTDA.,61.562.112/0001-20,PRICEWATERHOUSECOOPERS AUDITORES INDEPENDENTES LTDA.,30.306.294/0001-45,BANCO BTG PACTUAL S/A,NaN,NaN
67712,FUNCINE,32.222.962/0001-81,Fundo de Financiamento da Indústria Cinematográfica Nacional de Minas Gerais,2018-12-20,2018-11-14,418002.0,2021-10-29,CANCELADA,2021-10-29,NaN,...,INTRADER DTVM LTDA,PJ,09.544.103/0001-97,INVESTIMAGE ADMINISTRADORA DE RECURSOS LTDA.,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.,15.489.568/0001-95,INTRADER DTVM LTDA,NaN,NaN

>Buscando dados no site da CVM

###Manipulando os dados da CVM

>Definindo filtros para os Fundos de Investimento

In [67]:
minimo_cotistas = 100

>Manipulando os dados e aplicando filtros

In [70]:
fundos = informes_diarios[informes_diarios['NR_COTST'] >= minimo_cotistas ].pivot(index='DT_COMPTC', columns='CNPJ_FUNDO', values=['VL_TOTAL',	'VL_QUOTA',	'VL_PATRIM_LIQ',	'CAPTC_DIA',	'RESG_DIA'])

In [71]:
fundos

                     VL_TOTAL                                        \
CNPJ_FUNDO 00.068.305/0001-35 00.071.477/0001-68 00.073.041/0001-08
DT_COMPTC
2022-05-02        38604935.16       1.906791e+10        13332745.08
2022-05-03        38611491.79       1.846551e+10        13338096.36
2022-05-04        38594749.38       1.792601e+10        13343429.06
2022-05-05        38604242.10       1.719678e+10        13348507.06
2022-05-06        38606321.60       1.652200e+10        13353805.60
2022-05-09        38625296.42       1.605835e+10        13359677.10
2022-05-10        38586103.57       1.560230e+10        13364330.53
2022-05-11        38593214.25       1.529943e+10        13366448.81
2022-05-12        38564361.76       1.500173e+10        13370798.12
2022-05-13        38565894.19       1.469215e+10        13376565.19
2022-05-16        38518900.76       1.426148e+10        13382384.21

                                                                     \
CNPJ_FUNDO 00.089.915/0001-15 00.180.995/0001-10 00.185.259/0001-54
DT_COMPTC
2022-05-02        15977787.48       1.887085e+08       6.032434e+08
2022-05-03        15983837.43       1.889577e+08       5.994536e+08
2022-05-04        15985043.17       1.886217e+08       6.137275e+08
2022-05-05        15995972.68       1.883545e+08       5.962046e+08
2022-05-06        16002291.02       1.881130e+08       5.930525e+08
2022-05-09        15541460.39       1.879824e+08       5.782645e+08
2022-05-10        15734086.85       1.886349e+08       5.816176e+08
2022-05-11        15740586.75       1.885758e+08       5.830747e+08
2022-05-12        15422048.13       1.881339e+08       5.875290e+08
2022-05-13        15427422.95       1.872827e+08       5.965450e+08
2022-05-16        15572625.28       1.845300e+08       5.992375e+08

                                                                     \
CNPJ_FUNDO 00.222.725/0001-24 00.222.816/0001-60 00.280.302/0001-60
DT_COMPTC
2022-05-02        83695311.16       1.970675e+09       5.108788e+08
2022-05-03        82937478.68       1.965683e+09       5.105251e+08
2022-05-04        83290447.71       1.963719e+09       5.100509e+08
2022-05-05        83325726.57       1.957885e+09       5.106413e+08
2022-05-06        83362321.80       1.929816e+09       5.099094e+08
2022-05-09        83370003.02       1.921306e+09       5.085304e+08
2022-05-10        83397388.33       1.917497e+09       5.063037e+08
2022-05-11        83366048.79       1.913361e+09       5.081062e+08
2022-05-12        83387907.60       1.910618e+09       5.071530e+08
2022-05-13        83167727.47       1.905875e+09       5.068697e+08
2022-05-16        83197256.20       1.898413e+09       5.070430e+08

                               ...           RESG_DIA                     \
CNPJ_FUNDO 00.306.278/0001-91  ... 74.326.471/0001-20 77.054.658/0001-00
DT_COMPTC                      ...
2022-05-02       2.080577e+09  ...           82994.72               0.00
2022-05-03       2.072968e+09  ...            5880.42           15958.36
2022-05-04       2.073473e+09  ...            1796.51               0.00
2022-05-05       2.075867e+09  ...               0.00           15179.04
2022-05-06       2.073873e+09  ...             823.70               0.00
2022-05-09       2.069312e+09  ...           78993.74              19.48
2022-05-10       2.069671e+09  ...          112022.43               0.00
2022-05-11       2.070190e+09  ...            8705.83               0.00
2022-05-12       2.069052e+09  ...               0.00               0.00
2022-05-13       2.067666e+09  ...           40780.73               0.00
2022-05-16       2.068329e+09  ...               0.00               0.00

                                                                     \
CNPJ_FUNDO 88.002.696/0001-36 88.198.056/0001-43 96.498.654/0001-66
DT_COMPTC
2022-05-02             321.12           31247.13               0.00
2022-05-03            1648.28          196023.51            2919.53
2022-05-04             346.33          511069.39               0.00
2022-05-05            1750.57           63092.14            1291.36
2022-05-06            1680.60           68562.37            3338.20
2022-05-09            1606.75          187338.54               0.00
2022-05-10             994.21          147077.47               0.00
2022-05-11             652.46          730568.18            6700.55
2022-05-12             842.50           40356.36               0.00
2022-05-13            5528.08               0.00           93136.70
2022-05-16             656.39          102133.51          154954.79

                                                                     \
CNPJ_FUNDO 96.498.985/0001-04 96.500.715/0001-82 97.261.093/0001-40
DT_COMPTC
2022-05-02            1117.96               0.00               0.00
2022-05-03          154874.96               0.00               0.00
2022-05-04           18550.01         6992766.79            1000.00
2022-05-05            8966.15               0.00             342.96
2022-05-06               0.00               0.00            1017.17
2022-05-09               0.00               0.00          268970.51
2022-05-10               0.00               0.00           17098.06
2022-05-11               0.00               0.00             622.29
2022-05-12               0.00               0.00           53115.42
2022-05-13               0.00               0.00            1082.98
2022-05-16           23968.39               0.00             222.90


CNPJ_FUNDO 97.519.703/0001-62 97.519.794/0001-36
DT_COMPTC
2022-05-02         7655881.02          609727.37
2022-05-03         4319717.92           64407.87
2022-05-04        27600385.66          172165.21
2022-05-05          887884.06          385237.72
2022-05-06         4624682.74           52369.18
2022-05-09         3712154.61          181181.03
2022-05-10         3901651.41          442938.81
2022-05-11         6134317.67          365421.49
2022-05-12         1526813.37           27872.56
2022-05-13        26020380.54          316084.27
2022-05-16        17524386.08           38013.60

[11 rows x 18060 columns]

>Normalizando os dados de cotas para efeitos comparativos

In [74]:
cotas_normalizadas = fundos['VL_QUOTA'] / fundos['VL_QUOTA'].iloc[0]

In [75]:
cotas_normalizadas

CNPJ_FUNDO,00.068.305/0001-35,00.071.477/0001-68,00.073.041/0001-08,00.089.915/0001-15,00.180.995/0001-10,00.185.259/0001-54,00.222.725/0001-24,00.222.816/0001-60,00.280.302/0001-60,00.306.278/0001-91,...,74.326.471/0001-20,77.054.658/0001-00,88.002.696/0001-36,88.198.056/0001-43,96.498.654/0001-66,96.498.985/0001-04,96.500.715/0001-82,97.261.093/0001-40,97.519.703/0001-62,97.519.794/0001-36
DT_COMPTC,,,,,,,,,,,,,,,,,,,,,
2022-05-02,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2022-05-03,1.000390,1.000369,1.000399,1.000320,1.000347,0.993459,1.000388,1.000387,1.000501,1.000462,...,1.002166,0.998739,0.998899,0.998693,0.998007,0.998483,1.000371,1.004118,1.000485,1.000498
2022-05-04,1.001058,1.000744,1.000797,1.000698,1.000946,1.017059,1.000780,1.000907,1.001125,1.000922,...,1.009179,1.015450,1.016196,1.016582,1.018646,1.015320,1.000772,1.024497,1.000951,1.000988
2022-05-05,1.001454,1.001115,1.001183,1.001144,1.000905,0.989818,1.001214,1.001003,1.001395,1.001370,...,1.000046,0.987436,0.987083,0.988936,0.988656,0.986830,1.001182,1.004973,1.001535,1.001453
2022-05-06,1.001884,1.001517,1.001619,1.001586,1.001179,0.984874,1.001663,1.001419,1.001821,1.001850,...,1.005051,0.985612,0.984703,0.979398,0.986944,0.985189,1.001637,1.002186,1.002070,1.002054
2022-05-09,1.002319,1.001945,1.002057,1.001966,1.001707,0.960602,1.002117,1.001877,1.002257,1.002309,...,1.008981,0.964935,0.964755,0.958138,0.963823,0.967522,1.002099,0.979124,1.002586,1.002617
2022-05-10,1.002763,1.002362,1.002403,1.002464,1.002201,0.966129,1.002563,1.002337,1.002666,1.002792,...,1.015888,0.963975,0.964657,0.962630,0.969427,0.966145,1.002587,0.980631,1.003141,1.003122
2022-05-11,1.003290,1.002774,1.002839,1.002831,1.002690,0.968436,1.002975,1.003022,1.003389,1.003278,...,1.018114,0.976692,0.977236,0.967022,0.978271,0.978176,1.003068,1.001910,1.003682,1.003660
2022-05-12,1.003726,1.003183,1.003276,1.003261,1.003030,0.975724,1.003416,1.003490,1.003850,1.003777,...,1.022921,0.987123,0.988587,0.971328,0.989475,0.990265,1.003542,1.010377,1.004230,1.004185
2022-05-13,1.004161,1.003596,1.003713,1.003685,1.003448,0.990659,1.003858,1.004000,1.004397,1.004256,...,1.013920,0.997721,1.002022,0.991865,1.001996,1.001912,1.004006,1.026378,1.004702,1.004735
2022-05-16,1.004537,1.004007,1.004147,1.004104,1.004043,0.995182,1.004309,1.004550,1.004944,1.004745,...,1.005638,1.010680,1.013610,1.005430,1.010052,1.014126,1.004480,1.038738,1.005239,1.005211

###Fundos de Investimento com os melhores desempenhos em Maio de 2022

In [77]:
melhores = pd.DataFrame()
# ultimo dia do mes pegando os 5 primeiros fundos
melhores['retorno(%)'] = (cotas_normalizadas.iloc[-1].sort_values(ascending=False)[:5] - 1) * 100
melhores

                    retorno(%)
CNPJ_FUNDO
08.336.054/0001-34   14.295428
11.060.594/0001-42   14.179070
11.419.612/0001-30   14.059577
11.504.894/0001-73   14.004551
03.917.096/0001-45   13.860673

>Buscando dados dos Fundos de Investimento pelo CNPJ

In [78]:
for cnpj in melhores.index:
  fundo = cadastro_cvm[cadastro_cvm['CNPJ_FUNDO'] == cnpj]
  melhores.at[cnpj, 'Fundo de Investimento'] = fundo['DENOM_SOCIAL'].values[0]
  melhores.at[cnpj, 'Classe'] = fundo['CLASSE'].values[0]
  melhores.at[cnpj, 'PL'] = fundo['VL_PATRIM_LIQ'].values[0]

In [79]:
melhores

,retorno(%),Fundo de Investimento,Classe,PL
CNPJ_FUNDO,,,,
08.336.054/0001-34,14.295428,SICREDI - FUNDO DE INVESTIMENTO EM AÇÕES PETROBRAS,Fundo de Ações,1.360437e+08
11.060.594/0001-42,14.179070,FUNDO DE INVESTIMENTO EM AÇÕES CAIXA PETROBRAS PRÉ-SAL,Fundo de Ações,6.490168e+07
11.419.612/0001-30,14.059577,ITAÚ AÇÕES PETROBRÁS II FUNDO DE INVESTIMENTO,Fundo de Ações,3.544204e+06
11.504.894/0001-73,14.004551,BRADESCO FUNDO DE INVESTIMENTO EM AÇÕES - PETROBRAS 2010,Fundo de Ações,1.181710e+07
03.917.096/0001-45,13.860673,SANTANDER FI PETROBRÁS AÇÕES,Fundo de Ações,8.120124e+07

###Fundos de Investimento com os piores desempenhos em Abril de 2020

In [80]:
piores = pd.DataFrame()
piores['retorno(%)'] = (cotas_normalizadas.iloc[-1].sort_values(ascending=True)[:5] - 1) * 100
piores

                    retorno(%)
CNPJ_FUNDO
43.984.912/0001-58  -42.675900
43.508.446/0001-34  -29.561946
44.026.806/0001-24  -29.502743
41.545.885/0001-91  -28.068106
44.417.431/0001-23  -27.463458

>Buscando dados dos Fundos de Investimento pelo CNPJ

In [81]:
for cnpj in piores.index:
  fundo = cadastro_cvm[cadastro_cvm['CNPJ_FUNDO'] == cnpj]
  piores.at[cnpj, 'Fundo de Investimento'] = fundo['DENOM_SOCIAL'].values[0]
  piores.at[cnpj, 'Classe'] = fundo['CLASSE'].values[0]
  piores.at[cnpj, 'PL'] = fundo['VL_PATRIM_LIQ'].values[0]

In [82]:
piores

,retorno(%),Fundo de Investimento,Classe,PL
CNPJ_FUNDO,,,,
43.984.912/0001-58,-42.675900,VITREO CRIPTO SMART FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS DE INVESTIMENTO MULTIMERCADO IE,Fundo Multimercado,6596220.46
43.508.446/0001-34,-29.561946,VITREO COIN NFT FUNDO DE INVESTIMENTO MULTIMERCADO,Fundo Multimercado,8878624.90
44.026.806/0001-24,-29.502743,VITREO COIN SMART FUNDO DE INVESTIMENTO MULTIMERCADO,Fundo Multimercado,5722546.06
41.545.885/0001-91,-28.068106,VITREO COIN DEFI FUNDO DE INVESTIMENTO MULTIMERCADO,Fundo Multimercado,18036761.56
44.417.431/0001-23,-27.463458,HASHDEX ETHEREUM FUNDO DE INVESTIMENTO MULTIMERCADO,Fundo Multimercado,915812.04