<a href="https://colab.research.google.com/github/robertoricci/Analise-Financeira/blob/main/NOTEBOOK_ETL_B3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#instalar bibliotecas necessarias 
!pip install SQLAlchemy
!pip install psycopg2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: SQLAlchemy in /usr/local/lib/python3.7/dist-packages (1.4.44)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from SQLAlchemy) (4.13.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from SQLAlchemy) (2.0.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->SQLAlchemy) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->SQLAlchemy) (3.10.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: psycopg2 in /usr/local/lib/python3.7/dist-packages (2.9.5)

In [ ]:
import requests
from base64 import b64encode
import pandas as pd
import sqlalchemy as sql

In [ ]:
#criar conexão com o banco Postgres

conn = 'suaconexao'
sql_conn = sql.create_engine(conn)

In [ ]:
# Função para obter empresas do IBOV ou IFIX
def getEmpIndex(seg=2,index='IBOV'):
    # cria os parâmetros 
    # index: IBOV 
    #        IFIX

    #segment:1 informações sem segmento
    #       :2 informações com segmento

    params = {"language":"pt-br","pageNumber":1,"pageSize":200,"index":index,"segment":seg}
    
    # codifica os parâmetros em base64
    params = bytes(str(params), encoding="ascii")
    string = b64encode(params)
    string = string.decode()
   #{"language":"pt-br","pageNumber":1,"pageSize":120,"index":"IBOV","segment":"1"}

    r = requests.get('https://sistemaswebb3-listados.b3.com.br/indexProxy/indexCall/GetPortfolioDay/'+ string)
    return r.json()

In [ ]:
index = getEmpIndex()

In [ ]:
df_ibov = pd.DataFrame.from_dict(index['results'])

In [ ]:

#df_ibov[['segment','cod','asset','type']] = df_ibov[['segment','cod','asset','type']].astype(str)
#df_ibov['part'].apply(lambda x: float(x.replace(',', '.')))
#df_ibov['partAcum'].apply(lambda x: float(x.replace(',', '.')))
#df_ibov['theoricalQty'].apply(lambda x: float(x))
# df_ibov['segment'] = df_ibov['segment'].astype(str)
# df_ibov['cod'] = df_ibov['cod'].astype(str)
# df_ibov['asset'] =df_ibov['asset'].astype(str)
# df_ibov['type'] = df_ibov['type'].astype(str)
df_ibov['part']= df_ibov['part'].str.replace(',', '.',regex=True).astype(float)
df_ibov['partAcum'] = df_ibov['partAcum'].str.replace(',', '.',regex=True).astype(float)
df_ibov['theoricalQty'] = df_ibov['theoricalQty'].str.replace('.', '',regex=True).astype(int)

In [ ]:
df_ibov.dtypes

segment          object
cod              object
asset            object
type             object
part            float64
partAcum        float64
theoricalQty      int64
dtype: object

In [ ]:
#altera tipos das colunas

In [ ]:
df_ibov.set_index('cod')

,segment,asset,type,part,partAcum,theoricalQty
cod,,,,,,
WEGE3,Bens Indls / Máqs e Equips,WEG,ON NM,2.811,2.811,1481593024
EMBR3,Bens Indls / Mat Transporte,EMBRAER,ON NM,0.478,0.478,734632205
AZUL4,Bens Indls/Transporte,AZUL,PN N2,0.198,2.106,327646296
CCRO3,Bens Indls/Transporte,CCR SA,ON ED NM,0.607,2.106,1115681435
ECOR3,Bens Indls/Transporte,ECORODOVIAS,ON NM,0.074,2.106,333657615
...,...,...,...,...,...,...
ENGI11,Utilidade Públ / Energ Elétrica,ENERGISA,UNT N2,0.545,9.638,248477689
ENEV3,Utilidade Públ / Energ Elétrica,ENEVA,ON NM,0.994,9.638,1561135009
EGIE3,Utilidade Públ / Energ Elétrica,ENGIE BRASIL,ON NM,0.488,9.638,255208461
EQTL3,Utilidade Públ / Energ Elétrica,EQUATORIAL,ON NM,1.518,9.638,1100513485
TAEE11,Utilidade Públ / Energ Elétrica,TAESA,UNT N2,0.408,9.638,218568234

In [ ]:
df_ibov.dtypes

segment         object
cod             object
asset           object
type            object
part            object
partAcum        object
theoricalQty    object
dtype: object

In [ ]:
from sqlalchemy.sql.sqltypes import VARCHAR
#inserir no tabela
dtype = {'cod': sql.VARCHAR(10),'segment':sql.VARCHAR(100),'asset':sql.VARCHAR(20),'type':sql.VARCHAR(10),'part':sql.FLOAT,'partAcum':sql.FLOAT,'theoricalQty': sql.INT} 
df_ibov.to_sql('ibov_b3',sql_conn,schema='public',if_exists='append',index = False, method="multi",chunksize=999,dtype= dtype)

#importar dados do IFIX

In [ ]:
#buscar index do ifix
index_ifix = getEmpIndex(seg=2,index='IFIX')

In [ ]:
#tranformar em dataframe
df_ifix = pd.DataFrame.from_dict(index_ifix['results'])

In [ ]:
#converter colunas para formato desejado
df_ifix['part']= df_ifix['part'].str.replace(',', '.',regex=True).astype(float)
df_ifix['partAcum'] = df_ifix['partAcum'].str.replace(',', '.',regex=True).astype(float)
df_ifix['theoricalQty'] = df_ifix['theoricalQty'].str.replace('.', '',regex=True).astype(int)

In [ ]:
df_ifix.dtypes

segment          object
cod              object
asset            object
type             object
part            float64
partAcum        float64
theoricalQty      int64
dtype: object

In [ ]:
from sqlalchemy.sql.sqltypes import VARCHAR
#Criar tabela e inserir os dados
dtype = {'cod': VARCHAR(10),
         'segment':VARCHAR(100),
         'asset':VARCHAR(20),
         'type':VARCHAR(10),
         'part':FLOAT,
         'partAcum':FLOAT,
         'theoricalQty': INT} 
df_ifix.to_sql('ifix_b3',sql_conn,schema='public',if_exists='append',index = False, method="multi",chunksize=999,dtype= dtype)

In [ ]:
ifix_cursor = sql_conn.execute("SELECT * FROM public.ifix_b3")  
for r in ifix_cursor:  
    print(r)

('Financ e Outros / Fundos', 'CACR11', 'CARTESIA FII', 'CI  ER', 0.162, 100.0, 1807434.0)
('Financ e Outros / Fundos', 'BPFF11', 'FII ABSOLUTO', 'CI  ER', 0.273, 100.0, 4492326.0)
('Financ e Outros / Fundos', 'AFHI11', 'FII AFHI CRI', 'CI', 0.259, 100.0, 3019453.0)
('Financ e Outros / Fundos', 'ALZR11', 'FII ALIANZA', 'CI', 0.869, 100.0, 8310805.0)
('Financ e Outros / Fundos', 'ARCT11', 'FII ARCTIUM', 'CI', 0.324, 100.0, 3708168.0)
('Financ e Outros / Fundos', 'ARRI11', 'FII ATRIO', 'CI  ER', 0.095, 100.0, 11782610.0)
('Financ e Outros / Fundos', 'AIEC11', 'FII AUTONOMY', 'CI  ER', 0.32, 100.0, 4824987.0)
('Financ e Outros / Fundos', 'BARI11', 'FII BARIGUI', 'CI  ER', 0.395, 100.0, 4634191.0)
('Financ e Outros / Fundos', 'BBPO11', 'FII BB PRGII', 'CI  ER', 1.294, 100.0, 15919690.0)
('Financ e Outros / Fundos', 'BCFF11', 'FII BC FFII', 'CI  ER', 1.549, 100.0, 25186378.0)
('Financ e Outros / Fundos', 'BRCR11', 'FII BC FUND', 'CI  ER', 1.527, 100.0, 26638202.0)
('Financ e Outros / Fundos', 'BCIA11', 'FII BCIA', 'CI  ER', 0.297, 100.0, 3719038.0)
('Financ e Outros / Fundos', 'BCRI11', 'FII BEES CRI', 'CI  ER', 0.566, 100.0, 6257873.0)
('Financ e Outros / Fundos', 'BLMR11', 'FII BLUE FOF', 'CI  ER', 0.168, 100.0, 25541630.0)
('Financ e Outros / Fundos', 'BLMG11', 'FII BLUE LOG', 'CI  ER', 0.286, 100.0, 3810588.0)
('Financ e Outros / Fundos', 'BRCO11', 'FII BRESCO', 'CI  ER', 1.433, 100.0, 14778781.0)
('Financ e Outros / Fundos', 'BTAL11', 'FII BTG AGRO', 'CI', 0.52, 100.0, 5982736.0)
('Financ e Outros / Fundos', 'BTCR11', 'FII BTG CRI', 'CI  ER', 0.601, 100.0, 7418066.0)
('Financ e Outros / Fundos', 'BTRA11', 'FII BTG TAGR', 'CI', 0.262, 100.0, 3364559.0)
('Financ e Outros / Fundos', 'BTLG11', 'FII BTLG', 'CI', 1.516, 100.0, 16728960.0)
('Financ e Outros / Fundos', 'CPFF11', 'FII CAP REIT', 'CI  ER', 0.361, 100.0, 5449778.0)
('Financ e Outros / Fundos', 'CPTS11', 'FII CAPI SEC', 'CI', 2.547, 100.0, 31782814.0)
('Financ e Outros / Fundos', 'HGCR11', 'FII CSHG CRI', 'CI  ER', 1.799, 100.0, 19582397.0)
('Financ e Outros / Fundos', 'HGFF11', 'FII CSHG FOF', 'CI  ER', 0.198, 100.0, 2863597.0)
('Financ e Outros / Fundos', 'HGLG11', 'FII CSHG LOG', 'CI  ER', 3.486, 100.0, 23456675.0)
('Financ e Outros / Fundos', 'HGRU11', 'FII CSHG URB', 'CI  ER', 2.035, 100.0, 18406458.0)
('Financ e Outros / Fundos', 'CARE11', 'FII DEA CARE', 'CI', 0.117, 100.0, 35769919.0)
('Financ e Outros / Fundos', 'DEVA11', 'FII DEVANT', 'CI  ER', 1.21, 100.0, 15453965.0)
('Financ e Outros / Fundos', 'FEXC11', 'FII EXCELLEN', 'CI  ER', 0.474, 100.0, 6103509.0)
('Financ e Outros / Fundos', 'VRTA11', 'FII FATOR VE', 'CI  ER', 1.104, 100.0, 13152584.0)
('Financ e Outros / Fundos', 'GTWR11', 'FII G TOWERS', 'CI  ER', 0.872, 100.0, 12000000.0)
('Financ e Outros / Fundos', 'GGRC11', 'FII GGRCOVEP', 'CI  ERS', 0.914, 100.0, 8765433.0)
('Financ e Outros / Fundos', 'GALG11', 'FII GUARDIAN', 'CI  ER', 0.486, 100.0, 57485300.0)
('Financ e Outros / Fundos', 'HABT11', 'FII HABIT II', 'CI  ER', 0.68, 100.0, 8126783.0)
('Financ e Outros / Fundos', 'HCTR11', 'FII HECTARE', 'CI  ER', 1.982, 100.0, 22084202.0)
('Financ e Outros / Fundos', 'HGBS11', 'FII HEDGEBS', 'CI  ER', 1.812, 100.0, 10000000.0)
('Financ e Outros / Fundos', 'HGRE11', 'FII HG REAL', 'CI  ER', 1.393, 100.0, 11817767.0)
('Financ e Outros / Fundos', 'HSAF11', 'FII HSI CRI', 'CI  ER', 0.136, 100.0, 1773624.0)
('Financ e Outros / Fundos', 'HSLG11', 'FII HSI LOG', 'CI  ER', 1.057, 100.0, 12660067.0)
('Financ e Outros / Fundos', 'HSML11', 'FII HSI MALL', 'CI  ER', 1.246, 100.0, 15780613.0)
('Financ e Outros / Fundos', 'HFOF11', 'FII HTOPFOF3', 'CI  ER', 1.534, 100.0, 23000000.0)
('Financ e Outros / Fundos', 'FIIB11', 'FII INDL BR', 'CI  ER', 0.294, 100.0, 685000.0)
('Financ e Outros / Fundos', 'IRDM11', 'FII IRIDIUM', 'CI  ER', 3.181, 100.0, 36044581.0)
('Financ e Outros / Fundos', 'JSRE11', 'FII JS REAL', 'CI  ER', 1.506, 100.0, 20767328.0)
('Financ e Outros / Fundos', 'KISU11', 'FII KILIMA', 'CI  ER', 0.315, 100.0, 44196050.0)
('Financ e Outros / Fundos', 'KNRI11', 'FII KINEA', 'CI  ER', 3.03, 100.0, 24157121.0)
('Financ e Outros / Fundos', 'KNHY11', 'FII KINEA HY', 'CI  ER', 1.615, 100.0, 18490843.0)
('Financ e Outros / Fundos', 'KNIP11', 'FII KINEA IP', 'CI  ER', 6.724, 100.0, 80279611.0)
('Financ e Outros / Fundos', 'KNCR11', 'FII KINEA RI', 'CI  ER', 3.912, 100.0, 43861253.0)
('Financ e Outros / Fundos', 'KNSC11', 'FII KINEA SC', 'CI  ER', 1.038, 100.0, 13275794.0)
('Financ e Outros / Fundos', 'KFOF11', 'FII KINEAFOF', 'CI  ER', 0.345, 100.0, 4533315.0)
('Financ e Outros / Fundos', 'NSLU11', 'FII LOURDES', 'CI  ER', 0.185, 100.0, 1293286.0)
('Financ e Outros / Fundos', 'MALL11', 'FII MALLS BP', 'CI  ER', 0.919, 100.0, 9413575.0)
('Financ e Outros / Fundos', 'MCCI11', 'FII MAUA', 'CI', 1.635, 100.0, 18899883.0)
('Financ e Outros / Fundos', 'MCHF11', 'FII MAUA HF', 'CI', 0.263, 100.0, 32307646.0)
('Financ e Outros / Fundos', 'MXRF11', 'FII MAXI REN', 'CI  ER', 2.062, 100.0, 226039663.0)
('Financ e Outros / Fundos', 'MFII11', 'FII MERITO I', 'CI  ER', 0.361, 100.0, 4146900.0)
('Financ e Outros / Fundos', 'MGFF11', 'FII MOGNO', 'CI  ER', 0.512, 100.0, 9050620.0)
('Financ e Outros / Fundos', 'MORE11', 'FII MORE RE', 'CI', 0.147, 100.0, 2319115.0)
('Financ e Outros / Fundos', 'NCHB11', 'FII NCH BR', 'CI  ERS', 0.15, 100.0, 1821362.0)
('Financ e Outros / Fundos', 'OUJP11', 'FII OURI JPP', 'CI  ER', 0.277, 100.0, 3252384.0)
('Financ e Outros / Fundos', 'PATL11', 'FII PATR LOG', 'CI  ER', 0.34, 100.0, 4991535.0)
('Financ e Outros / Fundos', 'PLCR11', 'FII PLURAL R', 'CI  ER', 0.162, 100.0, 2109169.0)
('Financ e Outros / Fundos', 'PORD11', 'FII POLO CRI', 'CI  ER', 0.309, 100.0, 3728375.0)
('Financ e Outros / Fundos', 'QAGR11', 'FII QUASAR A', 'CI  ER', 0.211, 100.0, 5040000.0)
('Financ e Outros / Fundos', 'RBRL11', 'FII RBR LOG', 'CI  ER', 0.525, 100.0, 6687035.0)
('Financ e Outros / Fundos', 'RBRY11', 'FII RBR PCRI', 'CI  ER', 0.554, 100.0, 6374096.0)
('Financ e Outros / Fundos', 'RBRP11', 'FII RBR PROP', 'CI  ER', 0.595, 100.0, 12179186.0)
('Financ e Outros / Fundos', 'RBRF11', 'FII RBRALPHA', 'CI  ER', 0.894, 100.0, 13680770.0)
('Financ e Outros / Fundos', 'RBRR11', 'FII RBRHGRAD', 'CI  ER', 1.052, 100.0, 13438908.0)
('Financ e Outros / Fundos', 'RECR11', 'FII REC RECE', 'CI  ER', 2.079, 100.0, 26441650.0)
('Financ e Outros / Fundos', 'RECT11', 'FII REC REND', 'CI  ER', 0.435, 100.0, 8543493.0)
('Financ e Outros / Fundos', 'RBFF11', 'FII RIOB FF', 'CI  ER', 0.185, 100.0, 3749215.0)
('Financ e Outros / Fundos', 'RCRB11', 'FII RIOB RC', 'CI  ER', 0.443, 100.0, 3690695.0)
('Financ e Outros / Fundos', 'RBVA11', 'FII RIOB VA', 'CI  ER', 0.955, 100.0, 11588199.0)
('Financ e Outros / Fundos', 'RZAK11', 'FII RIZA AKN', 'CI  ES', 0.44, 100.0, 5007599.0)
('Financ e Outros / Fundos', 'RZTR11', 'FII RIZA TX', 'CI  ER', 1.003, 100.0, 11048018.0)
('Financ e Outros / Fundos', 'SADI11', 'FII SANT PAP', 'CI  ER', 0.258, 100.0, 3180207.0)
('Financ e Outros / Fundos', 'SARE11', 'FII SANT REN', 'CI  ER', 0.603, 100.0, 9234329.0)
('Financ e Outros / Fundos', 'SDIL11', 'FII SDI LOG', 'CI  ER', 0.546, 100.0, 6395050.0)
('Financ e Outros / Fundos', 'SPTW11', 'FII SP DOWNT', 'CI  ER', 0.069, 100.0, 1798000.0)
('Financ e Outros / Fundos', 'SNCI11', 'FII SUNO CRI', 'CI', 0.363, 100.0, 4104000.0)
('Financ e Outros / Fundos', 'SNFF11', 'FII SUNOFOFI', 'CI', 0.216, 100.0, 2775000.0)
('Financ e Outros / Fundos', 'TGAR11', 'FII TG ATIVO', 'CI  ER', 1.717, 100.0, 15336755.0)
('Financ e Outros / Fundos', 'TORD11', 'FII TORDE EI', 'CI  ER', 0.249, 100.0, 35051354.0)
('Financ e Outros / Fundos', 'TRXF11', 'FII TRX REAL', 'CI  ER', 0.943, 100.0, 9826045.0)
('Financ e Outros / Fundos', 'URPR11', 'FII URCA REN', 'CI  ER', 1.062, 100.0, 11858246.0)
('Financ e Outros / Fundos', 'VGHF11', 'FII VALOR HE', 'CI  ER', 0.604, 100.0, 72889247.0)
('Financ e Outros / Fundos', 'VGIP11', 'FII VALORAIP', 'CI', 0.941, 100.0, 11787247.0)
('Financ e Outros / Fundos', 'VGIR11', 'FII VALREIII', 'CI', 0.676, 100.0, 75707660.0)
('Financ e Outros / Fundos', 'CVBI11', 'FII VBI CRI', 'CI  ER', 0.893, 100.0, 11010228.0)
('Financ e Outros / Fundos', 'LVBI11', 'FII VBI LOG', 'CI  ER', 1.105, 100.0, 11775177.0)
('Financ e Outros / Fundos', 'PVBI11', 'FII VBI PRI', 'CI  ERS', 0.854, 100.0, 10039493.0)
('Financ e Outros / Fundos', 'RVBI11', 'FII VBI REIT', 'CI  ER', 0.098, 100.0, 1440000.0)
('Financ e Outros / Fundos', 'VCJR11', 'FII VECTIS', 'CI  ER', 1.22, 100.0, 14723970.0)
('Financ e Outros / Fundos', 'VSLH11', 'FII VERS CRI', 'CI  ER', 0.241, 100.0, 29864091.0)
('Financ e Outros / Fundos', 'VIFI11', 'FII VINCI IF', 'CI  ER', 0.054, 100.0, 8089190.0)
('Financ e Outros / Fundos', 'VIUR11', 'FII VINCI IU', 'CI  ER', 0.193, 100.0, 26946220.0)
('Financ e Outros / Fundos', 'VILG11', 'FII VINCI LG', 'CI  ER', 1.394, 100.0, 14997396.0)
('Financ e Outros / Fundos', 'VINO11', 'FII VINCI OF', 'CI  ER', 0.737, 100.0, 16565259.0)
('Financ e Outros / Fundos', 'VISC11', 'FII VINCI SC', 'CI  ER', 1.773, 100.0, 17696234.0)
('Financ e Outros / Fundos', 'VTLT11', 'FII VOT LOG', 'CI  ER', 0.18, 100.0, 2115000.0)
('Financ e Outros / Fundos', 'XPCI11', 'FII XP CRED', 'CI  ER', 0.681, 100.0, 8701552.0)
('Financ e Outros / Fundos', 'XPIN11', 'FII XP INDL', 'CI', 0.517, 100.0, 7150422.0)
('Financ e Outros / Fundos', 'XPLG11', 'FII XP LOG', 'CI  ER', 2.533, 100.0, 27101061.0)
('Financ e Outros / Fundos', 'XPML11', 'FII XP MALLS', 'CI', 1.934, 100.0, 21133278.0)
('Financ e Outros / Fundos', 'XPPR11', 'FII XP PROP', 'CI  ER', 0.246, 100.0, 7316171.0)
('Financ e Outros / Fundos', 'XPSF11', 'FII XP SELEC', 'CI  ER', 0.288, 100.0, 43302140.0)

In [ ]:
df_ifix  = ifix_cursor = sql_conn.execute("SELECT * FROM public.ifix_b3")

In [ ]:
#criar index na tabela 
sql_conn.execute(" ALTER TABLE PUBLIC.ifix_b3 add CONSTRAINT pk_ifix_b3 PRIMARY KEY (cod)")

In [ ]:
#select tabela converter para dataframe
df_ifix = pd.read_sql(""" SELECT * FROM public.ifix_b3 """, sql_conn)

In [ ]:
#select com where e converter para dataframe
df_ifix_one = pd.read_sql(""" SELECT * FROM public.ifix_b3  where "cod" = 'ARCT11' """, sql_conn)

In [ ]:
df_ifix_one

,segment,cod,asset,type,part,partAcum,theoricalQty
0,Financ e Outros / Fundos,ARCT11,FII ARCTIUM,CI,0.324,100.0,3708168

In [ ]:
df_ifix

,segment,cod,asset,type,part,partAcum,theoricalQty
0,Financ e Outros / Fundos,CACR11,CARTESIA FII,CI ER,0.162,100.0,1807434
1,Financ e Outros / Fundos,BPFF11,FII ABSOLUTO,CI ER,0.273,100.0,4492326
2,Financ e Outros / Fundos,AFHI11,FII AFHI CRI,CI,0.259,100.0,3019453
3,Financ e Outros / Fundos,ALZR11,FII ALIANZA,CI,0.869,100.0,8310805
4,Financ e Outros / Fundos,ARCT11,FII ARCTIUM,CI,0.324,100.0,3708168
...,...,...,...,...,...,...,...
103,Financ e Outros / Fundos,XPIN11,FII XP INDL,CI,0.517,100.0,7150422
104,Financ e Outros / Fundos,XPLG11,FII XP LOG,CI ER,2.533,100.0,27101061
105,Financ e Outros / Fundos,XPML11,FII XP MALLS,CI,1.934,100.0,21133278
106,Financ e Outros / Fundos,XPPR11,FII XP PROP,CI ER,0.246,100.0,7316171
107,Financ e Outros / Fundos,XPSF11,FII XP SELEC,CI ER,0.288,100.0,43302140

#Buscar todas as empresas listadas na B3

In [ ]:
def getAllCompanyB3(pageN=1,pageS=9999):
  
    params = {"language":"pt-br","pageNumber":pageN,"pageSize":pageS}
    # codifica os parâmetros em base64
    params = bytes(str(params), encoding="ascii")
    string = b64encode(params)
    string = string.decode()
    r = requests.get('https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetInitialCompanies/'+ string)

    return r.json()

In [ ]:
#resultado da API
result = getAllCompanyB3()

In [ ]:
df_allCompany = pd.DataFrame.from_dict(result['results'])

In [ ]:

#converter colunas para formato desejado
df_allCompany['codeCVM']= df_allCompany['codeCVM'].str.replace(',', '.',regex=True).astype(int)
df_allCompany['marketIndicator']= df_allCompany['marketIndicator'].str.replace(',', '.',regex=True).astype(int)
df_allCompany['dateListing'] = df_allCompany['dateListing'].str.replace('9999', '1900',regex=True).astype('datetime64[ns]')
df_allCompany['type'] = df_allCompany['type'].str.replace('.', '',regex=True).astype(int)
#df_allCompany['dateListing'] = df_allCompany['dateListing'].apply(lambda x: (parser.parse(x.replace('9999','1900')))).astype('datetime64[ns]')

In [ ]:
df_allCompany.dtypes

codeCVM                     int64
issuingCompany             object
companyName                object
tradingName                object
cnpj                       object
marketIndicator             int64
typeBDR                    object
dateListing        datetime64[ns]
status                     object
segment                    object
segmentEng                 object
type                        int64
market                     object
dtype: object

In [ ]:
df_allCompany.rename(columns = {'codeCVM':'codecvm'}, inplace = True)

In [ ]:
from sqlalchemy.sql.sqltypes import VARCHAR,INT
#inserir no tabela
dtype = {'codecvm': INT,
         'issuingCompany':VARCHAR(10),
         'companyName':VARCHAR(200),
         'tradingName':VARCHAR(50),
         'marketIndicator':INT,
         'typeBDR':VARCHAR(20),
         'dateListing':DateTime,
         'status': VARCHAR(1),
         'segment':	VARCHAR(100),
         'segmentEng':VARCHAR(100),
         'type':INT,
         'market':VARCHAR(20)
         } 

df_allCompany.to_sql('company_b3',sql_conn,schema='public',if_exists='append',index = False, method="multi",chunksize=999,dtype= dtype)

In [ ]:
pd.read_sql(" select codecvm from PUBLIC.company_b3 ",sql_conn)

,codecvm,issuingCompany,companyName,tradingName,cnpj,marketIndicator,typeBDR,dateListing,status,segment,segmentEng,type,market
0,25291,RRRP,3R PETROLEUM ÓLEO E GÁS S.A,3R PETROLEUM,12091809000155,18,,2020-09-11,A,Exploração. Refino e Distribuição,Exploration. Refining and Distribution,1,NM
1,908830,TZRD,3Z REALTY DESENVOLVIMENTO IMOBILIARIO S/A,3ZREALTY,8145855000112,1,,1900-12-31,A,Não Classificados,Not Classified,7,
2,16284,QVQP,524 PARTICIPACOES S.A.,524 PARTICIP,1851771000155,7,,1998-11-09,A,Outros,Others,1,MB
3,904110,GRDR,A GERADORA ALUGUEL DE MAQUINAS S.A.,GERADORA,33845322000190,1,,1900-12-31,A,Não Classificados,Not Classified,7,
4,901082,BODY,A BODYTECH PARTICIPACOES S.A.,BODYTECH,7737623000190,1,,1900-12-31,A,Não Classificados,Not Classified,7,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2251,914804,ZZDT,Z.A DIGITAL SP SIST. ESTACIONAMENTO ROTARIVO S.A.,Z.A DIGITAL,35993098000100,1,,1900-12-31,A,Não Classificados,Not Classified,7,
2252,24317,ZAMP,ZAMP S.A.,ZAMP S.A.,13574594000196,18,,2017-12-14,A,Restaurante e Similares,Restaurants and Similars,1,NM
2253,915249,ZTIX,ZATIX TECNOLOGIA S.A.,ZATIX TECNOL,3585974000172,1,,1900-12-31,A,Não Classificados,Not Classified,7,
2254,909655,ZMPT,ZEMA CIA. DE PETROLEO,ZEMA,647154000170,1,,1900-12-31,A,Não Classificados,Not Classified,7,
2255,909648,ZION,ZION CAPITAL S.A.,ZIONCAPITAL,27080444000130,1,,1900-12-31,A,Não Classificados,Not Classified,7,

In [ ]:
#criar index
#criar index na tabela 
sql_conn.execute(" ALTER TABLE PUBLIC.company_b3 add CONSTRAINT pk_company_b3 PRIMARY KEY (codecvm) ")

#buscar detalhes das empresas

In [ ]:
def getDetailCompany(codeCVM):
  
    params = {"codeCVM":codeCVM,"language":"pt-br"}
    # codifica os parâmetros em base64
    params = bytes(str(params), encoding="ascii")
    string = b64encode(params)
    string = string.decode()
    r = requests.get('https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetDetail/'+ string)

    return r.json()

In [ ]:
sql = "SELECT codecvm from PUBLIC.company_b3  WHERE codecvm != 26700 AND codecvm NOT IN ( SELECT codecvm FROM PUBLIC.detail_company_b3) LIMIT 500 "

cvms = pd.read_sql(sql,sql_conn)

In [ ]:
cvms.shape

(457, 1)

In [ ]:
from sqlalchemy.sql.sqltypes import VARCHAR,INT,FLOAT,DateTime,TEXT,NUMERIC,JSON
dtype = {'issuingcompany':VARCHAR(10),
         'companyName':VARCHAR(200),
         'tradingName':VARCHAR(100),
         'CNPJ':VARCHAR(20),
         'industryClassification': VARCHAR(200),
         'industryClassificationEng': VARCHAR(200),
         'activity':VARCHAR(200),
         'website':VARCHAR(100),
         'hasQuotation':VARCHAR(100),
         'status': VARCHAR(1),
         'marketIndicator':INT,
         'institutionCommon':VARCHAR(100),
         'institutionPreferred':VARCHAR(100),
        'code':	VARCHAR(10),
        'codecvm': INT,
        'lastdate':DateTime,
        'otherCodes':	JSON,
        'hasEmissions':Boolean,
        'hasBDR':Boolean,
        'typeBDR':VARCHAR(100),
        'describleCategoryBVMF':VARCHAR(200)
      }

In [ ]:
import time
from datetime import datetime

all_detail_company = pd.DataFrame()
err_cvm = []
print(datetime.today())
for i in cvms.index:
    cod = cvms['codecvm'][i]
    print(cod)
    time.sleep(1)
    result = getDetailCompany(cod)
    #separar em as chaves e depois os valores para montar o dataframe

    if (len(result) == 0):
       err_cvm.append(cod)
       continue

    values = result.values()
    keys = result.keys()

    df_detCompany = pd.DataFrame([values],columns=keys)

    #converter colunas para formato desejado
    df_detCompany['codeCVM']= df_detCompany['codeCVM'].str.replace(',', '.',regex=True).astype(int)
    df_detCompany['marketIndicator']= df_detCompany['marketIndicator'].str.replace(',', '.',regex=True).astype(int)
    df_detCompany['lastDate'] = df_detCompany['lastDate'].astype('datetime64[ns]')
    df_detCompany.rename(columns = {'codeCVM':'codecvm','issuingCompany':'issuingcompany'}, inplace = True)

    #df_allCompany['dateListing'] = df_allCompany['dateListing'].apply(lambda x: (parser.parse(x.replace('9999','1900')))).astype('datetime64[ns]')

    all_detail_company =  pd.concat([all_detail_company,df_detCompany])
    print(cod)
all_detail_company.to_sql('detail_company_b3',sql_conn,schema='public',if_exists='append',index = False, method="multi",chunksize=999,dtype=dtype)
    
print(datetime.today())
print('empresa não encontrada')
print(err_cvm)

2022-11-12 18:01:23.500812
913376
913376
913384
913384
913392
913392
913400
913400
913418
913418
913426
913426
913434
913434
913442
913442
913459
913459
913467
913467
913475
913475
913483
913483
913491
913491
913509
913509
913517
913517
913525
913525
913533
913533
913541
913541
913558
913558
913566
913566
913574
913574
913582
913582
913590
913590
913608
913608
913616
913616
913624
913624
913632
913632
913640
913640
913657
913657
913665
913665
913673
913673
913681
913681
913699
913699
913749
913749
913756
913756
913764
913764
913772
913772
913780
913780
913798
913798
913806
913806
913814
913814
913822
913822
913830
913830
913848
913848
913889
913889
913897
913897
913905
913905
913913
913913
913921
913921
913939
913939
913947
913947
913954
913954
913962
913962
913970
913970
913988
913988
913996
913996
914028
914028
914036
914036
914044
914044
914051
914051
914077
914077
914085
914085
914093
914093
914101
914101
914119
914119
914127
914127
914135
914135
914143
914143
914176
914176
914184
914184
914192
914192
914200
914200
914218
914218
914226
914226
914234
914234
914242
914242
914259
914259
914267
914267
914275
914275
914283
914283
914291
914291
914309
914309
914317
914317
914325
914325
914333
914333
914341
914341
914358
914358
914366
914366
914374
914374
914382
914382
914390
914390
914408
914408
914416
914416
914424
914424
914432
914432
914440
914440
914457
914457
914473
914473
914481
914481
914499
914499
914507
914507
914515
914515
914523
914523
914531
914531
914549
914549
914556
914556
914564
914564
914572
914572
914580
914580
914598
914598
914648
914648
914655
914655
914663
914663
914671
914671
914689
914689
914697
914697
914705
914705
914713
914713
914739
914739
914747
914747
914788
914788
914796
914796
914804
914804
914812
914812
914820
914820
914838
914838
914846
914846
914853
914853
914861
914861
914879
914879
914887
914887
914895
914895
914903
914903
914911
914911
914929
914929
914937
914937
914945
914945
914952
914952
914960
914960
914978
914978
914986
914986
914994
914994
915058
915058
915066
915066
915074
915074
915082
915082
915090
915090
915108
915108
915116
915116
915124
915124
915132
915132
915140
915140
915199
915199
915207
915207
915215
915215
915223
915223
915231
915231
915249
915249
915256
915256
915264
915264
915272
915272
915280
915280
915298
915298
915306
915306
915314
915314
915322
915322
915330
915330
915348
915348
915355
915355
915363
915363
915371
915371
915389
915389
915397
915397
915405
915405
915413
915413
915421
915421
915439
915439
915447
915447
915454
915454
915462
915462
915470
915470
915488
915488
915496
915496
915504
915504
915512
915512
915520
915520
915538
915538
915546
915546
915553
915553
915561
915561
915579
915579
915587
915587
915595
915595
915603
915603
915611
915611
915652
915652
915660
915660
915678
915678
915686
915686
915694
915694
915702
915702
915710
915710
915728
915728
915736
915736
915744
915744
915751
915751
915801
915801
915819
915819
915827
915827
915835
915835
915843
915843
915850
915850
915868
915868
915876
915876
915884
915884
915892
915892
915900
915900
915918
915918
915926
915926
915934
915934
915967
915967
915975
915975
915983
915983
915991
915991
916007
916007
916015
916015
916023
916023
916031
916031
916049
916049
916098
916098
916106
916106
916114
916114
916122
916122
916130
916130
916148
916148
916153
916155
916161
916163
916171
916172
916173
916174
916175
916188
916189
916196
916197
916205
916213
916221
916239
916247
916254
916262
916270
916288
916296
916304
916312
916320
916338
916346
916353
916361
916379
916382
916387
916390
916395
916403
916411
916429
916437
916445
916452
916460
916478
916486
916494
916502
916551
916569
916577
916585
916593
916595
916601
916619
916627
916633
916635
916641
916643
916700
916714
916718
916722
916730
916749
916757
916765
916773
916781
916791
916809
916811
916825
916833
916838
916841
916846
916854
916858
916862
916870
916889
916897
916908
916919
916927
916935
916943
916951
916957
916965
916978
916986
916994
917005
917013
917021
917039
917047
917054
917062
917070
917088
917096
917104
917112
917120
917133
917141
917146
917146
917153
917161
917179
917187
917195
917203
917229
917237
917245
917252
917260
917278
917286
917294
917302
917310
917328
917336
917344
917351
917362
917370
917389
917397
917401
917450
917452
917453
917454
917455
917456
917457
917458
917459
917461
917462
917463
917464
917465
917466
917467
917468
917469
917470
917471
917472
917473
917474
917475
917476
917477
917479
917480
917481
917482
917483
917484
917485
917487
917488
917489
917490
917491
917492
917493
917495
917496
917497
917498
917499
917500
917501
917502
917503
917504
917505
917506
917507
917509
917510
917511
917512
917513
917514
917515
917517
917518
917519
917520
917521
917522
917523
917525
917526
917527
917528
917529
917530
917531
917533
917534
917535
917536
917537
917538
917539
917541
917542
917543
917544
917545
917546
2022-11-12 18:13:53.155384
codigo com erro
[916153, 916155, 916161, 916163, 916171, 916172, 916173, 916174, 916175, 916188, 916189, 916196, 916197, 916205, 916213, 916221, 916239, 916247, 916254, 916262, 916270, 916288, 916296, 916304, 916312, 916320, 916338, 916346, 916353, 916361, 916379, 916382, 916387, 916390, 916395, 916403, 916411, 916429, 916437, 916445, 916452, 916460, 916478, 916486, 916494, 916502, 916551, 916569, 916577, 916585, 916593, 916595, 916601, 916619, 916627, 916633, 916635, 916641, 916643, 916700, 916714, 916718, 916722, 916730, 916749, 916757, 916765, 916773, 916781, 916791, 916809, 916811, 916825, 916833, 916838, 916841, 916846, 916854, 916858, 916862, 916870, 916889, 916897, 916908, 916919, 916927, 916935, 916943, 916951, 916957, 916965, 916978, 916986, 916994, 917005, 917013, 917021, 917039, 917047, 917054, 917062, 917070, 917088, 917096, 917104, 917112, 917120, 917133, 917141, 917153, 917161, 917179, 917187, 917195, 917203, 917229, 917237, 917245, 917252, 917260, 917278, 917286, 917294, 917302, 917310, 917328, 917336, 917344, 917351, 917362, 917370, 917389, 917397, 917401, 917450, 917452, 917453, 917454, 917455, 917456, 917457, 917458, 917459, 917461, 917462, 917463, 917464, 917465, 917466, 917467, 917468, 917469, 917470, 917471, 917472, 917473, 917474, 917475, 917476, 917477, 917479, 917480, 917481, 917482, 917483, 917484, 917485, 917487, 917488, 917489, 917490, 917491, 917492, 917493, 917495, 917496, 917497, 917498, 917499, 917500, 917501, 917502, 917503, 917504, 917505, 917506, 917507, 917509, 917510, 917511, 917512, 917513, 917514, 917515, 917517, 917518, 917519, 917520, 917521, 917522, 917523, 917525, 917526, 917527, 917528, 917529, 917530, 917531, 917533, 917534, 917535, 917536, 917537, 917538, 917539, 917541, 917542, 917543, 917544, 917545, 917546]

In [ ]:
#df_detCompany['otherCodes']=  df_detCompany['otherCodes'].apply(lambda x: ((x.replace("[","").replace("]",""))))
#import json
#df_detCompany['otherCodes'] = df_detCompany['otherCodes'].apply(json.dumps)

#importar dados dos fundos imobiliarios

In [ ]:
import requests
from base64 import b64encode
# Função para obter os proventos
def getFii(pageN=1,pageS=999):
  
    # cria os parâmetros com o trading name

    params = {"typeFund":7,"pageNumber":pageN,"pageSize":pageS}
    
    # codifica os parâmetros em base64
    params = bytes(str(params), encoding="ascii")
    string = b64encode(params)
    string = string.decode()

    r = requests.get('https://sistemaswebb3-listados.b3.com.br/fundsProxy/fundsCall/GetListedFundsSIG/'+string)
    return r.json()

In [ ]:
fii = getFii()

In [ ]:
df_all_fii = pd.DataFrame.from_dict(fii['results'])

In [ ]:
df_all_fii.rename(columns = {'fundName':'fundname','companyName':'companyname'}, inplace = True)

In [ ]:
#from sqlalchemy.sql import VARCHAR
dtype = {'segment':VARCHAR(10),
         'acronym':VARCHAR(50),
          'fundname':VARCHAR(50),
         'companyname':VARCHAR(200),
         'cnpj':VARCHAR(20),
      }

In [ ]:
#gravar no banco SQL
df_all_fii.to_sql('fii_b3',sql_conn,schema='public',if_exists='append',index = False, method="multi",chunksize=999,dtype=dtype)

Buscar detalhes dos fundos imobiliarios

In [ ]:
import requests
from base64 import b64encode
# Função para obter os proventos
def getDetailFii(acronym):
  
    # codFII: "ASRF"
    params =   {"typeFund":7,"identifierFund":acronym}
    # codifica os parâmetros em base64
    params = bytes(str(params), encoding="ascii")
    string = b64encode(params)
    string = string.decode()

    r = requests.get('https://sistemaswebb3-listados.b3.com.br/fundsProxy/fundsCall/GetDetailFundSIG/'+string)
    return r.json()

In [ ]:
df = getDetailFii('KNHY')

In [ ]:
#buscar nome dos fii na base de dados
# buscar todos empresas cadastrada na base de dados para fazer o SPLIT no campo industryclassification !!
sql = " SELECT distinct(acronym) FROM PUBLIC.fii_b3 WHERE acronym NOT IN (SELECT distinct(acronym) FROM  PUBLIC.detail_fii_b3)  "
def_fii = pd.read_sql(sql,sql_conn)

In [ ]:
def_fii

Empty DataFrame
Columns: [acronym]
Index: []

In [ ]:
from sqlalchemy.sql.sqltypes import VARCHAR,INT,FLOAT,DateTime,TEXT,NUMERIC,JSON
dtype = {'acronym': VARCHAR(10),
          'tradingname': VARCHAR(30),
          'tradingcode': VARCHAR(10),
          'tradingcodeothers': VARCHAR(50),
          'cnpj': VARCHAR(20),
          'classification': VARCHAR(200),
          'website': VARCHAR(100),
          'fundaddress': VARCHAR(200),
          'fundphonenumberddd': VARCHAR(20),
          'fundphonenumber': VARCHAR(20),
          'fundphonenumberfax': VARCHAR(20),
          'positionmanager':  VARCHAR(50),
          'managername':  VARCHAR(50),
          'companyaddress': VARCHAR(200),
          'companyphonenumberddd': VARCHAR(10),
          'companyphonenumber': VARCHAR(20),
          'companyphonenumberfax': VARCHAR(20),
          'companyemail': VARCHAR(100),
          'companyname': VARCHAR(100),
          'quotacount': INT,
          'quotadateapproved': DateTime,
          'typefnet': VARCHAR(50),
          'codes': JSON,
          'codesother': VARCHAR(50),
          'segment': VARCHAR(50)
          }

In [ ]:

#key = list(df_fii.columns)
#value = [x.lower() for x in list(df_fii.columns)]
##columns = pd.DataFrame([value],columns=key).to_dict('records')[0]

import time
from datetime import datetime

err_det_fii = []
print(datetime.today())
for i in def_fii.index:
    cod = def_fii['acronym'][i]
    print(cod)
    time.sleep(2)
    #buscar detalhes dos fundos
    result = getDetailFii(cod)
  

    if (len(result['detailFund']) == 0):
       err_det_fii.append(cod)
       continue
    #renomear colunas com em lower case
    columns = { 'acronym': 'acronym',
               'tradingName': 'tradingname',
              'tradingCode': 'tradingcode',
              'tradingCodeOthers': 'tradingcodeothers',
              'cnpj': 'cnpj',
              'classification': 'classification',
              'webSite': 'website',
              'fundAddress': 'fundaddress',
              'fundPhoneNumberDDD': 'fundphonenumberddd',
              'fundPhoneNumber': 'fundphonenumber',
              'fundPhoneNumberFax': 'fundphonenumberfax',
              'positionManager': 'positionmanager',
              'managerName': 'managername',
              'companyAddress': 'companyaddress',
              'companyPhoneNumberDDD': 'companyphonenumberddd',
              'companyPhoneNumber': 'companyphonenumber',
              'companyPhoneNumberFax': 'companyphonenumberfax',
              'companyEmail': 'companyemail',
              'companyName': 'companyname',
              'quotaCount': 'quotacount',
              'quotaDateApproved': 'quotadateapproved',
              'typeFNET': 'typefnet',
              'codes': 'codes',
              'codesOther': 'codesother',
              'segment': 'segment' }

    df_fii = pd.DataFrame([result['detailFund']])
    df_fii.rename(columns = columns, inplace = True)
    df_fii['cnpj'] =  df_fii['cnpj'].astype(int)
    df_fii['quotacount'] =  df_fii['quotacount'].astype(int)
    df_fii['quotadateapproved'] = pd.to_datetime( df_fii['quotadateapproved'], errors ='coerce')
    df_fii.fillna('')
    df_fii.to_sql('detail_fii_b3',sql_conn,schema='public',if_exists='append',index = False, method="multi",dtype=dtype)
    
      
print(datetime.today())
print('não existem detalhes')
print(err_det_fii)

2022-11-18 21:41:33.800859
ABCP
FLMA
MOFF
LFTT
HUSI
CJFI
SHDP
BCRI
HLOG
RBRY
JFLL
SFND
CCME
GURB
VIDS
FIIP
BVAR
XPCI
PLOG
HGCR
VLJS
TEPP
RBVA
FMOF
GGRC
KNHY
BTSG
SIGR
RBHG
VLIQ
VCJR
VDSV
TSNC
RBLG
CTNP
SOLR
RBRM
AFHI
MTOF
OURE
MMPD
AURB
BRCR
DEVA
CYCR
PRSN
JPPA
ARRI
RCKF
FIIB
BRIP
ALZM
CCRF
KISU
YUFI
NAVT
PRTS
FPAB
MORC
JCDB
TCIN
IRDM
FAMB
XPIN
HTMX
FAGL
EVBI
ZAVI
HCHG
CXCE
TRXF
PRSV
JTPR
QAMI
HCRI
XPPR
IDFI
FCFL
CEOC
TRXB
KFOF
VSLH
RRCI
SPVJ
CPFF
FLRP
IBCR
RVBI
FEXC
BARI
BMLC
BRSE
DVFF
IRIM
EDGA
HGFF
MVFI
NEWL
RBIR
HCTR
RECX
LRDI
PQAG
BRCO
BBRC
TGAR
FIGS
BZEL
RPRI
PNDL
BBPO
2022-11-18 21:49:07.211682
não existem detalhes
[]

# Atualizar o Setor/Subsetor e Segmento da empresas listada na B3

In [ ]:
# buscar todos empresas cadastrada na base de dados para fazer o SPLIT no campo industryclassification !!

sql = " SELECT * FROM PUBLIC.detail_company_b3  WHERE industryclassification IS NOT NULL "

empresas = pd.read_sql(sql,sql_conn)

In [ ]:
empresas[["setor","subsetor","segmento"]] = empresas["industryclassification"].str.split("/",expand=True)

In [ ]:
empresas

,issuingcompany,companyname,tradingname,cnpj,industryclassification,industryclassificationEng,activity,website,hasquotation,status,...,othercodes,hasemissions,hasbdr,typebdr,describleCategorybvmf,datelisting,lastdate,setor,subsetor,segmento
0,WEGE,WEG S.A.,WEG,84429695000111,Bens Industriais / Máquinas e Equipamentos / M...,None,A WEG SA é uma sociedade de participação não o...,www.weg.net/br,None,A,...,"[{'code': 'WEGE3', 'isin': 'BRWEGEACNOR0'}]",False,False,None,None,2022-11-11 23:41:58,2022-11-11 23:41:58,Bens Industriais,Máquinas e Equipamentos,Motores . Compressores e Outros
1,ENER,ENERGISA MATO GROSSO DO SUL - DIST DE ENERGIA ...,ENERSUL,15413826000150,Utilidade Pública / Energia Elétrica / Energia...,None,Distribuição de energia elétrica,www.enersul.com.br,None,A,...,None,False,False,None,None,2022-11-11 23:18:00,2022-11-11 23:18:00,Utilidade Pública,Energia Elétrica,Energia Elétrica
2,ETER,ETERNIT S.A.,ETERNIT,61092037000181,Bens Industriais / Construção e Engenharia / P...,None,Industrialização e comercialização de produtos...,www.eternit.com.br/ri,None,A,...,"[{'code': 'ETER3', 'isin': 'BRETERACNOR3'}]",False,False,None,None,2022-11-11 23:18:53,2022-11-11 23:18:53,Bens Industriais,Construção e Engenharia,Produtos para Construção
3,EUCA,EUCATEX S.A. INDUSTRIA E COMERCIO,EUCATEX,56643018000166,Materiais Básicos / Madeira e Papel / Madeira,None,Indústria e Comércio de chapas de fibra de mad...,www.eucatex.com.br/ri,None,A,...,"[{'code': 'EUCA3', 'isin': 'BREUCAACNOR1'}, {'...",False,False,None,None,2022-11-11 23:18:55,2022-11-11 23:18:55,Materiais Básicos,Madeira e Papel,Madeira
4,FIGE,INVESTIMENTOS BEMGE S.A.,INVEST BEMGE,01548981000179,Outros / Outros / Outros,None,Investimentos,www.investimentosbemge.com.br,None,A,...,"[{'code': 'FIGE3', 'isin': 'BRFIGEACNOR6'}, {'...",False,False,None,None,2022-11-11 23:23:25,2022-11-11 23:23:25,Outros,Outros,Outros
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2029,TCUL,TERRA DE CULTIVO INDS. DE FERT. E RACOES LTDA,TERRAINDSLTD,06105854000119,Não Classificados / Não Classificado / Não Cla...,None,None,,None,A,...,None,False,False,None,None,NaT,2022-11-11 23:38:14,Não Classificados,Não Classificado,Não Classificados
2030,DETR,TRAVESSIA E DELTA SEC. DE CREDITOS MERCANTIS S.A.,TRAVDELTASEC,41719223000190,Não Classificados / Não Classificado / Não Cla...,None,None,,None,A,...,None,False,False,None,None,NaT,2022-11-11 23:38:58,Não Classificados,Não Classificado,Não Classificados
2031,ALEX,ALEX ENERGIA PARTICIPACOES S.A.,ALEXENERGIAP,31908068000105,Não Classificados / Não Classificado / Não Cla...,None,None,,None,A,...,None,False,False,None,None,NaT,2022-11-11 23:04:38,Não Classificados,Não Classificado,Não Classificados
2032,THAP,THALASSIUS A033.21 PARTICIPAÇÕES S.A,THALASSIUSA0,42152864000179,Não Classificados / Não Classificado / Não Cla...,None,None,,None,A,...,None,False,False,None,None,NaT,2022-11-11 23:38:22,Não Classificados,Não Classificado,Não Classificados
2033,EMSA,EMS S.A.,EMS,57507378000365,Não Classificados / Não Classificado / Não Cla...,None,None,,None,A,...,None,False,False,None,None,NaT,2022-11-11 23:17:43,Não Classificados,Não Classificado,Não Classificados

In [ ]:
from sqlalchemy.sql.sqltypes import VARCHAR,INT,FLOAT,DateTime,TEXT,NUMERIC,JSON,Boolean
dtype = {'issuingcompany': VARCHAR(10),
         'companyname':VARCHAR(200),
         'tradingname':VARCHAR(100),
         'cnpj': VARCHAR(20),
         'industryclassification': VARCHAR(200),
         'industryclassificationEng': VARCHAR(200),
         'activity':VARCHAR(200),
         'website':VARCHAR(100),
         'hasquotation':VARCHAR(100),
         'status': VARCHAR(1),
         'marketindicator':INT,
         'institutioncommon':VARCHAR(100),
         'institutionpreferred':VARCHAR(100),
         'code':	VARCHAR(10),
         'codecvm': INT,
         'lastdate':DateTime,
         'othercodes':	JSON,
         'hasemissions':Boolean,
         'hasbdr':Boolean,
         'typebdr':VARCHAR(100),
         'describlecategorybvmf': VARCHAR(200),
         'setor':VARCHAR(100),
         'subsetor':VARCHAR(100),
         'segmento':VARCHAR(100)
      } 
#empresas.to_sql('detail_company_b3',sql_conn,schema='public',if_exists='replace',index = False, method="multi",dtype=dtype)

In [ ]:
# formar tabela de setor 
sql = " SELECT distinct(setor) as descricao FROM PUBLIC.detail_company_b3  WHERE industryclassification IS NOT NULL order by setor "
df_setores = pd.read_sql(sql,sql_conn)

In [ ]:
from sqlalchemy.sql.sqltypes import VARCHAR,INT
#criar uma coluna a partir do index
df_setores = df_setores['descricao'].str.strip()
df_setores = df_setores.rename_axis('codigo').reset_index()
#deixar o index a partir de 1
df_setores['codigo'] = df_setores['codigo']+1

dtype = {'codigo':INT,
         'descricao':VARCHAR(100)
}

#criar a tabela no banco
df_setores.to_sql('setores_b3',sql_conn,schema='public',if_exists='replace',index = False, method="multi",dtype=dtype)

In [ ]:
# formar tabela de subserto
sql = " SELECT distinct(subsetor) as descricao FROM PUBLIC.detail_company_b3  WHERE industryclassification IS NOT NULL order by subsetor "
df_subsetores = pd.read_sql(sql,sql_conn)

In [ ]:
df_subsetores = df_subsetores['descricao'].str.strip().replace('Não Classificados','Não Classificado').drop_duplicates()
df_subsetores = df_subsetores.rename_axis('codigo').reset_index()
df_subsetores['codigo'] = df_setores['codigo']+1
dtype = {'codigo':INT,
         'descricao':VARCHAR(100)
}
#criar a tabela no banco
df_setores.to_sql('subsetores_b3',sql_conn,schema='public',if_exists='replace',index = False, method="multi",dtype=dtype)

In [ ]:
# criar tabela de segmentos
sql = " SELECT distinct(segmento) as descricao FROM PUBLIC.detail_company_b3  WHERE industryclassification IS NOT NULL order by segmento "
df_segmento = pd.read_sql(sql,sql_conn)

In [ ]:
#df_segmento.groupby(['descricao']).size().sort_values()
#remover duplicadas e limpar espaço em brancos
df_segmento['descricao'] = df_segmento['descricao'].str.strip().drop_duplicates()
###
df_segmento = df_segmento.rename_axis('codigo').reset_index()
df_segmento['codigo'] = df_segmento['codigo'] + 1
dtype = {'codigo':INT,
          'descricao':VARCHAR(100)
}
# #criar a tabela no banco
df_segmento.to_sql('segmentos_b3',sql_conn,schema='public',if_exists='replace',index = False, method="multi",dtype=dtype)

#buscar dados dos dividendos dos ativos

In [ ]:
def tipo_acao(tipo):
      if tipo == 'ON':
        vTipo = 3
      elif tipo == 'PN':
        vTipo = 4
      elif tipo == 'PNA':
        vTipo = 5
      elif tipo == 'PNB':
        vTipo = 6
      elif tipo == 'UNIT':
        vTipo = 11
      else:
         vTipo = ''

      return vTipo

In [ ]:
# Função para obter os proventos
def dividendos(tradingname):
    # cria os parâmetros com o trading name
    params = {"language":"pt-br","pageNumber":1,"pageSize":99999,"tradingName":tradingname}
    # codifica os parâmetros em base64
    params = bytes(str(params), encoding="ascii")
    string = b64encode(params)
    string = string.decode()
    r = requests.get('https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetListedCashDividends/'+ string)

    return r.json()

In [ ]:
# buscar tabelas de company
sql = " SELECT codecvm, tradingname, issuingcompany FROM public.company_b3 WHERE codecvm not in (SELECT  distinct(codecvm) FROM PUBLIC.dividendos_b3) AND codecvm IN  (SELECT  distinct(codecvm) FROM PUBLIC.detail_company_b3 WHERE code IS NOT null) order by codecvm "
df_company = pd.read_sql(sql,sql_conn)
df_company['tradingname']   = df_company['tradingname'].str.replace('/','').str.replace(' ','')

In [ ]:
#list_erro =  ['HERCULES', 'HOTEISOTHON', 'ESTRELA', 'IGUATEMIS.A', 'NORDONMET', 'SPTURIS', 'WETZELSA', 'SANSUY', 'HAGASA', 'CEMEPE', 'SUZANOS.A.', 'DIBENSLSG', 'CIMS', 'P.ACUCAR-CBD', 'LITEL', 'ALLNORTE', 'FERCATLANT', '524PARTICIP', 'SUL116PART', 'SUDESTESA', 'EQTLMARANHAO', 'UPTICK', 'YBYRASA', 'BNDESPAR', 'RUMOS.A.', 'BETAPART', 'MMXMINER', 'ALLPAULISTA', 'MRSLOGIST', 'GAMAPART', 'CONFIANZASA', 'CIBRASEC', 'PROMPTPART', 'RBCAPITALRES', 'PADTEC', 'WTORREPIC', 'MENEZESCORT', 'DTCOM-DIRECT', 'BRAZILIANSC', 'INVEPAR', 'CABINDAPART', 'CONCRIOTER', 'PROMAN', 'BIOMM', 'ITAPEBI', 'SANESALTO', 'BRADESCOLSG', 'BRAZILREALT', 'TERMOPE', 'BRPR56SEC']

In [ ]:
df_company = df_company.query('tradingname not in @list_erro')

In [ ]:

import time
from datetime import datetime

all_div = pd.DataFrame()
err_div = []
print(datetime.today())
for i in df_company.index:
    cod = df_company['tradingname'][i]
    print(cod)
    time.sleep(2)
    result = dividendos(cod)
    
    #separar em as chaves e depois os valores para montar o dataframe

    if (len(result['results']) == 0):
       err_div.append(cod)
       continue

    df_proventos = pd.DataFrame(result['results'])
        #transformar as colunas nos types necessario

    #renomear as colunas
    df_proventos.rename(columns = {'typeStock':'typestock',
                                  'dateApproval':'dateapproval',
                                   'valueCash':'valuecash',
                                   'corporateAction':'corporateaction',
                                   'lastDatePriorEx':'lastdatepriorex',
                                   'dateClosingPricePriorExDate':'dateclosingpricepriorexdate',
                                   'closingPricePriorExDate':'closingpricepriorexdate',
                                   'quotedPerShares':'quotedpershares',
                                    'corporateActionPrice':'corporateactionprice',
                                   'lastDateTimePriorEx':'lastdatetimepriorex'}, inplace = True)
    
    df_proventos['codecvm'] = df_company['codecvm'][i]
    df_proventos['tradingname'] = df_company['tradingname'][i]
    df_proventos['code'] = df_proventos['typestock'].apply(lambda x: (df_company['issuingcompany'][i]+str(tipo_acao(x))))
    df_proventos['valuecash'] = df_proventos['valuecash'].str.replace('.','',regex=True).str.replace(',','.',regex=True).astype(float)
    
    df_proventos['closingpricepriorexdate'] = df_proventos['closingpricepriorexdate'].str.replace('.','',regex=True).str.replace(',','.',regex=True).astype(float)
    df_proventos['corporateactionprice'] = df_proventos['corporateactionprice'].str.replace('.','',regex=True).str.replace(',','.',regex=True).astype(float)
    
    #df_proventos['lastdatepriorex'] = df_proventos['lastdatepriorex'].astype('datetime64[ns]')
    df_proventos['lastdatepriorex'] = pd.to_datetime( df_proventos['lastdatepriorex'] , errors ='coerce')
    try:
       #df_proventos['dateclosingpricepriorexdate'] = df_proventos['dateclosingpricepriorexdate'].astype('datetime64[ns]')
       df_proventos['dateclosingpricepriorexdate'] = pd.to_datetime( df_proventos['dateclosingpricepriorexdate'] , errors ='coerce')
    except Exception:
      df_proventos['dateclosingpricepriorexdate'] = ''
       	
    #df_proventos['lastdatetimepriorex'] =     df_proventos['lastdatetimepriorex'].astype('datetime64[ns]')

    df_proventos['lastdatetimepriorex'] = pd.to_datetime( df_proventos['lastdatetimepriorex'] , errors ='coerce')

    #df_proventos['dateapproval'] = df_proventos['dateapproval'].astype('datetime64[ns]')
    df_proventos['dateapproval'] = pd.to_datetime( df_proventos['dateapproval'] , errors ='coerce')

    df_proventos.fillna('')

    #all_div =  pd.concat([all_div,df_proventos])

    df_proventos.to_sql('dividendos_b3',sql_conn, schema='public',if_exists='append',index = False, method="multi", dtype=dtype)

    # #criar a tabela no banco
#all_div.to_sql('dividendos_b3',sql_conn, schema='public',if_exists='append',index = False, method="multi", dtype=dtype)   
print(datetime.today())
print('não existem dividendos')
print(err_div)

2022-11-18 16:38:15.771962
BKRSHORTTR
BKR13YRTR
BKR20YRTRS
ABDENSILV
ABDENGOLD
PMCO1T5YRT
PMCOBROAD
PMCO15YRTP
PMCOIGRCPI
PCOM0T5HY
PCOM25YRZC
BKRCOREHDV
BKRGBSTAMP
BKRCHINAA
BKRSAUDARAB
BKRSPSM600V
BKRCODISCRT
BKRCYBTECH
BKRMORTGAGE
BKREURPFNC
BKRRESMULTS
BKRSELFDRIV
BKRCOSTAPLE
BKRGENOIMM
BKRLOWCARBO
BKRGBMMPRD
BKRROBTAIM
BKRGBSDVGO
BKRUSINFRA
BKRUSUTILT
GXSP500CC
GXRUS2000CC
GXSUDIVREIT
GXMSCIGREEC
GXMSCICHIFL
GXCANNABIS
JPBTBCANAD
JPBTBREIT
JPRETUINTL
JPBTBRETUR
JPBTBUSEQ
JPQLTFACT
JPDIVRETUS
JPDVUSEME
JPUSVLFAC
JPDVUSMID
JPUSMOFAC
JPDVUSSM
GXBLOCKCHAI
GXCLEANCH
PIMCOMFEME
WTCLOUCOMP
VANECKEMERG
VANECKANGL
VANECKPREF
STONECO
XPINC
INTERCO
GOLDTRUST
MSCIEAFE
MSCIEMGMARK
MSCIASIAJP
SELECTDIVID
SILVERTRUST
RUSSELL2000
CORESPTOTA
MSCIUSMVOL
MSCIUK
MSCIGERMANY
MSCIMEXICO
MSCISPAIN
USAEROSPACE
LATINAMER40
CORESP500
MSCIACWI
COREMSCIEAFE
COREMSCIEMK
USTECHNOLOG
MSCIJAPAN
USFINANCIAL
MSCICHINA
GLOBALINFRA
EXPONTECHNL
TRUSTMSCIUS
TRTMSCIEAFE
INCESGAWAR
ICEBIOTECH
COREMIDCAP
CORESMALLCAP
PREFERINCOME
GLOBALHEALTH
GLOBALTECH
MSCISOUTHKOR
MSCIHONGKONG
MSCITAIWAN
MSCIINDIA
MSCIBRAZIL
MSCIEUROZONE
COREMSCIEUR
EUROPEETF
SP500VALUE
SP500GROWTH
MSCIMINVOLF
CURHEDGEMSCI
MSCIUSAMOMF
MSCIEMMRKMI
MSCIUSQUALF
MSCIUSASIZF
USMEDICDEVIC
MSCIEAFEGROW
MSCIUSVALUEF
USFINANCSERV
MSCIEAFEVALU
RUSSEL1000GR
COREDIVGROWT
MSCIGLMIVOLF
CHINALARGECA
MSCICANADA
MSCIAUSTRALI
MSCISWITZER
MSCIFRANCE
COREUSREIT
GLOBALREIT
ESGMSCIUSAL
FTEQOPPORT
FTINTLEQOP
FTMORDVLEA
FTNASDCYBER
FTNATGAS
FTLCAPGROW
FTCAPSTRENG
FTNASD100EQ
FTNASD100TC
FTRISIDIVID
FTCLOUDCPT
FTNYSEBIOT
FTDJINTERN
JPBTBEUROP
JPBTBJAPAO
JPBTBINTL
JPBTBASIA
GXINTERTHGS
GXGENOMBIOT
GXMILLECONM
FTVLINEDIV
FTHCAREALPH
FTTECHALPH
BKRSP100
BKRGLFIN
BKRUSENER
BKRMSRUSS
BKRMSEAFE
BKRSEMICOND
BKRGLCLEAN
BKRMSWLD
BKRMSUSAS
VESTEELETF
VEBUZZETF
VEMOATETF
VEGOLDETF
GPINVEST
PPLA
AURA360
G2DINVEST
NU-NUBANK
AGROPARAME
MANAUSHOTEL
PAGRISA
FARTURAAGRO
FIACSANTON
SIMARA
PRAIAHOTEL
TBM
ALLFAMA
INDDUREINO
OYAMOTABR
ALUMAZON
PBHATIVOS
AQUARIO
AMATA
ABAPORTO
ABIMEX
ABAPORU
ACECOTI
CAMBORIUSPE
ADAMI
GRUAINVEST
AGEO
AGUASTRIUNFO
AGROVIA
NITEROI
AGUASPARAIBA
AGIPLANCFI
AGUASSAOFRAN
TIMONSAN
AGUTIERREZ
ALESAT
ALGAR
ALIANCA
ALMEIDA
ALUBAM
ALUSAENG
AMAM
ARMAZEMMATEU
ANDORINHA
PENHASPE
ARMCO
ARTECOLA
ARAUCARIA
ASCENTYSA
ATIVAS
ATENTOBRASIL
ATEMS
ATLANTIC
ATERPA
ATRIUMEMP
ATIVOS
ATVOSAGRO
AUCKLAND
AURATUS
ALPHAVILLEU
SINOP
PAG
AZULAEREAS
AJRENNERBM
BAUERRJ
BCOCETELEMBM
BELEMBIO
DBSA
BCOB3BC
BRASBUNKER
BBOSA
MERCEDESBENZ
BRKBDTVM
CAPITALBM
ITAUVEICULOS
CARGILLBM
GMACBM
HONDABM
CHINABM
DAYLEASBM
AGRICOLEBM
BCLV
ABNBM
CSFBM
VRBM
CAIXAGERALBM
BANCOFIDISBM
FIBRABM
BIOFLEX
FORDBM
CIFRABM
BINGENSEC
JSLAM
BRADESCARDBM
SUISSEBI
BIOPARACATU
BIZCAPITAL
KEBBC
BROOKFIELDEN
BELOMONTE
MAXINVESTBM
BMSA
BMCHYUNDAI
MERRILLLYNCH
BAUMINASLOG
ORIGINALBM
MAXIMABC
LANACIONARGE
BANDADECOURO
MELLONDTVM
ITAUCONSBM
BONSUCESSOCO
BNYMELLONBC
BODYTECH
BORGATO
OMNIBM
BRASILPLURAL
CREFISABC
PSAFINANCEBM
BRBCFI
BARCAS
BRADOSA
RODOBENSBM
BARAUNASII
BRITANIA
BRAINFARMA
BARIGUICH
BRKCFI
BRKCENTRONOR
BBAM
BRPARTNERSBI
BRASHOPSA
BRAVOBEEFSA
BRVIAS
SAFRABM
BSME
INBURSABM
BTGHOLDING
MUFGBM
DSBSERVICOS
BCOTOYOTABM
VOLKSWAGENBM
VOLVOBM
CABAGUASAGRE
AGUASCUIABA
PARANAGUA
CALDEIRAO
ABRILEDUCACA
CIASERVICOS
FLORIANOPOLI
CAIUAENERGIA
CARUANACFI
PREMIUM
BAHIANORTE
CIABRAVIDROS
CCAB
CAMCORPART
BBNEGBM
CAMARGO
CAMARGOINFRA
CIDADANIA
CERENERGIAS
CODEMIG
CREDITACFI
CEAII
NEOENERGIADI
ECO135
CEJA
CAETITEPART
CEOSADM
EPESA
CERAN
CERRADINHO
CELSESERGIPE
LUZDOOESTE
CAMPOFORMOSO
COMFRIO
CONTOUR
COPACABANA
CHBCH
CHAPADAI
CIBE
CIMAR
CINEL
CIPASA
CITIBM
CLASSICOBM
BRINOX
CALAMO
COLUMBIA
CALANGO6
CLARINDOPART
CAPIMBRANCO
CAMPOII
CIAPARANA
MOVESP
CANABRAVA
ENERGCANDEIA
CAMPOSNOVOS
CNHCAPITALBM
LINHA4
CALOINORTE
CONASA
CODEME
CONE
COTIAVITORIA
CPFLCOMERCBR
CPFL
CIAJAGUARI
COPELSA
CIAALCOOL
COMPORTEPART
CPQBRASIL
RBCAP
COPELTELE
CAMPOSVENTOS
ETCCAPIXABA
CONSTRUTORAG
BRAZILIENSE
CREDZ
CROMEX
CAPRICORNIO
CROMOSSOMOII
CORUMBA
CARUANAPART
CSBIO
CIFRACFI
ENOVA
CARTAGOIAS
COTEMINASSA
ENERTOCANTIN
VIARIO
CATERPILLARB
CETREL
CANTAREIRA
CAVANROCBRA
CASAEVIDEO
MORRINHOSENE
CAMACARI
DOBREVE
DEUTSCHEBM
MERCEDESBBM
DELGA
DELTA5
DELTA6
CLINICADELFI
DGBGEO
DROGARIASP
DICCKER
DIANABIOENER
DOBREVEPART
COMERCIALSA
SCOTIABANKBM
PRINCIPALDSB
DATORA
DIVCOM
TAIBAAGUIA
EOLICATAIBA
ANGICAL
EATE
ESTALEIROSUL
EBAM
EOLICAFEIJAO
EOLICAFEIJAO
EOLICAFEIJAO
EOLICAFEIJAO
SEMEARBM
EBRASIL
EBTEEMP
VISTAALEGRE
ECOGEN
COLONIA
COQUEIRINHO
ECORODOANEL
PEDRARAJADA
CORRUPIAO
ECTESA
CAITITU
CONCESSIONAR
ATICA
EDUCAMAIS
EDUCACIONAL
EDPALIANCASC
EDPRENOVAVEI
EDPTRANSMISS
EDPCENTRAIS
SCIPIONE
ENELEOLICA
ENERGIAVENTO
ICARAII
ICARAIII
INHAMBU
ELFAMED
ELEJOR
ELOG
ELECTRA
SERRA
VACASII
SERRADASVACA
EOLICAVERMEL
EOLICAVACASI
SERRADASVACA
ELETROZEMA
ENELGREEN
ENELBRASIL
ENERGEST
ENELSUDESTE
ENERPEIXE
EMPRESANORTE
VENTOSII
VENTOSI
EOLBRISA
EOLVENTO
EOLWIND
SAOCRISTOVAO
SAOJORGE
STOANTONIOPA
EOLICAVACAS
EPASA
VENTOSX
VENTOSIII
SAOMANUEL
PROPERTYBR
USINAESTER
SERRADASVACA
VACASV
ETAPPOTIGUAR
ALTOURUGUAI
ETC
EMPRPARAENSE
ETES
EOLICATAMAND
ESTREAMBIENT
VARZEAGRANDE
EOLICAVACAVI
EXPANSION
EXTREMOZ
FABZOSA
FATPART
ACEF
FACTACFI
FORCAEOLICA
FLAFLU
FGRURBANISMO
FICSABM
LUIZACREDCFI
ITAUCREDBM
FONTENOVA
FOZ
RECIFEGOIANA
FRANCISCO
FRAPORTBR
FORTBRASIL
FOSPAR
STARACFI
FATORBM
FYP
SOMOSENSINO
GALILEOSA
GAREN
GASMIG
GASVERDE
GBXTIETE
CEUAZUL
GAIACREDIISE
GAIACREDIVSE
GAIACREDIIIS
AGRESTE
ALVORADA
JARDINS
MACAMBIRAI
GOODFOOD
GIOVANNIENER
GOLFVILLAGE
VENTOSDASERR
GALVAOPART
MACAMBIRAII
GMRENERGIA
GUANABARABM
GUANHAES
SGFINANCEAM
GRANINV
ALGARTI
GERADORA
GOLDMANSACHS
GSPLIFE
GSPSPE
GASTERPART
SPE
HONDAAM
HEINZBR
HERMES
CHPALTOCANTI
HELIOBORENST
LAFARGEHOLCI
HORTIGIL
CARVALHOHOSK
KIRTONBM
LOSANGOBM
HSINVESTIMEN
ESPERANCA
HTLSPPART
HAZTEC
RIOIACO
BRADCARBM
IBMBM
IDIBRA
MADEIRA
HAITONGBI
IPIRANGAPROD
INFRAMERICA
IRACEMA
IRONHOUSE
IRTHA
ISAIBRASIL
ISOLUXPART
ITAUCARDBM
CBSSBM
BBABM
INTERCAPBM
ITAREMAENERG
ITAPOA
JAURUENERGIA
ORIGINALAGRO
JCPMPARTICIP
CIAJACAREZIN
JEFINVEST
JOTAELE
JFLVHOUSE
JHSFMANAUS
JMALUC
MORGANBC
JPMORGANBM
MOVIDAGEST
KINGFOOD
KURUMA
KUHN
LAGEBM
EOLICALAGOA
LOCAR
LCEHPART
LOCALFRIO
EOLICALAN
BIOSEVDIS
LETSRENTACAR
LOGA
LAGOA1
LAGOPEDRAPAR
CIALIGNA
LDI
LINHARESSA
LAJEADOENERG
LOJASLEADER
PORTOACU
LAMBDAENERG
ANDBANKBM
METROSAOPAUL
LINEA
LOGEPRINT
LOGPRINT
LONGFORD
LSHBARRA
LEASEPLANAM
MONTESCLAROS
TAUBATE
LUFTPART
LUSOBRASILEI
MARACANA
MAIAEBORBA
MARAENERGIA
MBEXPANSAO
ESTRELACFI
MCARAIBA
MARTINSDIST
MDLREALTY
MADRIPART
MILOINVEST
MINVEST
MILANOCOMERC
MILANO
MARLIN
MULTILOG
MMSPARTICIPA
PORTOBRASIL
MMXSUDESTE
MINASARENA
MANAUSAMBIEN
MANDIC
BRASOILPETRO
MANTIQUEIRA
MONTREAL
MORRINHOS
MARACANAU
MERCANTII
MARECHALRON
MRLENGENHARI
MOROCO
MORGANSTANLE
STAGENEBRA
MSPARTICIPAC
METRODABAHIA
MTELTECSA
METROBARRA
METRONORTE
MATEUS
MULTITERMINA
MATAVELHA
MUDARSPESA
MOVIDALOC
MVPARTICIPAC
MARISOL
XINGUPART
NATIXISBM
NBCBM
NCENERGIA
NOTREDAME
COMPNACIONAL
NEERANS
NUFARM
NEGRESCOCFI
NAMPONT
NORTEBR
NS2
MAISSHOPPING
NORTEENERGIA
NATURALONE
NOVANTS
VENTOFORMOSO
CHAPEUENERGI
PONTOCOM
NOVAVENTOS
NVTIANGUA
TIANGUANORTE
OAS
OCEANAIR
OCEAN
ODEBRECHTAMB
BRKSUMARE
BRKAMBIENTAL
ODEBRECHTPAR
ODEBRECHTTRA
ODEBSA
ODEBENER
ORSA
ODEBRETRANS
ODOYAENERGIA
VENTOARAGANO
EOLICA2
OESTADO
OEAEOLICAIV
SENANDESIII
ODEBPARTINV
OMEGA2
OUROPRETO
OURINVESTBM
OSPINVEST
OSX
PACER
PORTALEGREPA
EOLICAPARAIS
RECII
PORTODOPECEM
BAHIAPCH
PCHHOLDING
PEDRAII
PEDRAI
PDCPART
PDL10
RECI
PARNAIBAGAS
PARTPHARMA
C2
PIRAPORAIIEN
PEDRARAJADAI
POLO
PRIMAVCONST
PRIMEINC
BARCASENERGI
SALGADO
PARNAIBAENER
PIRAPORAIX
PORTONAVEPAR
PIRAPORAIVEN
PIRAPORAVI
ASSURUA
LARANJEIRASI
ASSURUAVII
LARANJEIRASI
ASSURUAII
PARKEMPREE
PROQUIGEL
PIRAPORAIIIE
PIRAPORAII
PIRAPORAX
PARQUEDALAGO
PIRAPORAV
PRUDENSHOPPI
PROSIMULADOR
PARANAIBA
SANTFINANCEA
POUSOALEGRE
PNEUSOLA
PORTOCREDCFI
POTIGUAR
POTAMIENERGI
PORTONAVE
PETRA
PIRAPORAVII
QUALICORPADM
QUALICORSEG
QUEIROZDEV
QUEIROZGALVA
QGALVAO
Q1COMERCIAL
QUEIXADA
ATLANTICO
RABOBANKBM
RBCOMMERCIAL
RBCAPHOLDING
RIBEIRAOPRET
PRIMEII
REALTYIX
RBS
REALTYVII
RIACHUELO
REC2017IX
REC2017VI
RODLAGOS
CONCESRODOES
RODOVIACATAR
REBSA

KeyboardInterrupt: ignored

In [ ]:
#all_div.to_sql('dividendos_b3',sql_conn, schema='public',if_exists='append',index = False, method="multi", dtype=dtype)